apiVersion: v1
kind: Service
metadata:
  name: cli-deliverer
  labels:
    app: cli-deliverer
spec:
  type: ClusterIP
  selector:
    app: cli-deliverer
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000