apiVersion: v1
kind: Service
metadata:
  name: rca-producer
  labels:
    app: rca-producer-root
spec:
  type: NodePort
  selector:
    app: rca-producer-root
  ports:
    - protocol: TCP
      nodePort: 30908
      targetPort: 7055
      port: 7055