apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer1-producer
  labels:
    app: peer1-producer
spec:
  selector:
    matchLabels:
      app: peer1-producer
  template:
    metadata:
      labels:
        app: peer1-producer
    spec:
      containers:
        - name: peer1-producer
          image: hyperledger/fabric-peer:2.2
          volumeMounts:
            - mountPath: /tmp/hyperledger/producer/peer1
              name: peer1-producer-mount
          envFrom:
          - configMapRef:
              name: producer-peer1-env-file
          - secretRef:
              name: producer-peer1-secret-file
      volumes:
        - name: peer1-producer-mount
          hostPath:
            path: /hyperledger/producer/peer1
