apiVersion: v1
kind: Service
metadata:
  name: frontend-retailer
  labels:
    app: frontend-retailer
spec:
  type: ClusterIP
  selector:
    app: frontend-retailer
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-retailer
  labels:
    app: frontend-retailer
spec:
  selector:
    matchLabels:
      app: frontend-retailer
  template:
    metadata:
      labels:
        app: frontend-retailer
    spec:
      containers:
        - name: frontend-retailer
          image: frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: retailer-frontend-env-file
