apiVersion: apps/v1
kind: Deployment
metadata:
    name: couchdb2
    labels:
        app: couchdb2
spec:
    selector:
        matchLabels:
            app: couchdb2
    template:
        metadata: 
            labels:
                app: couchdb2
        spec:
            containers:
              - name: couchdb2
                image: couchdb:latest
                imagePullPolicy: IfNotPresent
                envFrom:
                  - secretRef:
                        name: couchdb2-secret-file