apiVersion: v1
kind: Service
metadata:
  name: couchdb2
  labels:
    app: couchdb2
spec:
  type: ClusterIP
  selector:
    app: couchdb2
  ports:
    - protocol: TCP
      targetPort: 5984
      port: 5984