apiVersion: v1
kind: Service
metadata:
  name: rca-retailer
  labels:
    app: rca-retailer-root
spec:
  type: NodePort
  selector:
    app: rca-retailer-root
  ports:
    - protocol: TCP
      nodePort: 30911
      targetPort: 7058
      port: 7058