apiVersion: apps/v1
kind: Deployment
metadata:
    name: rca-retailer
    labels:
        app: rca-retailer-root
spec:
    selector:
        matchLabels:
            app: rca-retailer-root
    template:
        metadata: 
            labels:
                app: rca-retailer-root
        spec:
            containers:
              - name: rca-retailer
                image: hyperledger/fabric-ca:1.4.7
                imagePullPolicy: IfNotPresent
                command: ["fabric-ca-server", "start", "-b", "$(RCA_ADMIN_USERNAME):$(RCA_ADMIN_PASSWORD)", "--port", "7058"]
                volumeMounts:
                  - mountPath: /tmp/hyperledger/fabric-ca
                    name: ca-mount
                envFrom:
                  - configMapRef:
                      name: retailer-ca-env-file
                  - secretRef:
                      name: retailer-ca-secret-file
            volumes:
              - name: ca-mount
                hostPath:
                  path: /hyperledger/retailer/ca