apiVersion: v1
kind: Service
metadata:
  name: cli-manufacturer
  labels:
    app: cli-manufacturer
spec:
  type: ClusterIP
  selector:
    app: cli-manufacturer
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000