apiVersion: v1
kind: Service
metadata:
  name: cli-producer
  labels:
    app: cli-producer
spec:
  type: ClusterIP
  selector:
    app: cli-producer
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-producer
  labels:
    app: cli-producer
spec:
  selector:
    matchLabels:
      app: cli-producer
  template:
    metadata:
      labels:
        app: cli-producer
    spec:
      containers:
        - name: cli-producer
          image: cli
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          tty: true
          workingDir: /tmp/hyperledger/chaincode
          volumeMounts:
            - mountPath: /tmp/hyperledger/producer/admin
              name: producer-admin-mount
            - mountPath: /tmp/hyperledger/producer/peer1
              name: producer-peer1-mount
            - mountPath: /tmp/hyperledger/scripts
              name: scripts-mount
            - mountPath: /tmp/hyperledger/chaincode
              name: chaincode-mount
            - mountPath: /tmp/hyperledger/shared
              name: shared-mount
            - mountPath: /tmp/hyperledger/app
              name: app-mount
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 3
          env:
            - name: GOPATH
              value: "/opt/gopath"
            - name: CORE_VM_ENDPOINT
              value: "unix:///host/var/run/docker.sock"
            # Uncomment for debugging
            #- name: FABRIC_LOGGING_SPEC
            #  value: "DEBUG"
            - name: CORE_PEER_ID
              value: "cli-producer"
            - name: CORE_PEER_ADDRESS
              value: "peer1-producer:7051"
            - name: CORE_PEER_LOCALMSPID
              value: "ProducerMSP"
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/tmp/hyperledger/producer/peer1/tls-msp/tlscacerts/${PEERS_TLSCACERTS}"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/tmp/hyperledger/producer/admin/msp"
            - name: ANCHOR_PEER_IP
              value: "peer1-producer"
            - name: ANCHOR_PEER_PORT
              value: "7051"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "toor"
            - name: DB_HOST
              value: "cli-producer-db"
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: "admin"
            - name: RCA_ADMIN_USERNAME
              value: "rca-producer-admin"
            - name: RCA_ADMIN_PASSWORD
              value: "rca-producer-adminpw"
            - name: ADMIN_USERNAME
              value: "admin-producer"
            - name: ADMIN_PASSWORD
              value: "producerAdminPW"
            - name: ORG_CA_HOST
              value: "rca-producer"
            - name: ORG_MSP_ID
              value: "ProducerMSP"
      volumes:
        - name: producer-peer1-mount
          hostPath:
            path: /hyperledger/producer/peer1
        - name: producer-admin-mount
          hostPath:
            path: /hyperledger/producer/admin
        - name: chaincode-mount
          hostPath:
            path: /hyperledger/chaincode
        - name: scripts-mount
          hostPath:
            path: /hyperledger/scripts
        - name: shared-mount
          hostPath:
            path: /hyperledger/shared
        - name: docker-mount
          hostPath:
            path: /var/run/
        - name: app-mount
          hostPath:
            path: /hyperledger/app/producer-cli
