apiVersion: v1
kind: Service
metadata:
  name: cli-producer
  labels:
    app: cli-producer
spec:
  type: ClusterIP
  selector:
    app: cli-producer
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-producer
  labels:
    app: cli-producer
spec:
  selector:
    matchLabels:
      app: cli-producer
  template:
    metadata:
      labels:
        app: cli-producer
    spec:
      containers:
        - name: cli-producer
          image: cli
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
          - configMapRef:
              name: producer-cli-env-file
          - secretRef:
              name: producer-cli-secret-file
          tty: true
          workingDir: /tmp/hyperledger/chaincode
          volumeMounts:
            - mountPath: /tmp/hyperledger/producer/admin
              name: producer-admin-mount
            - mountPath: /tmp/hyperledger/producer/peer1
              name: producer-peer1-mount
            - mountPath: /tmp/hyperledger/shared
              name: shared-mount
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 3
      volumes:
        - name: producer-peer1-mount
          hostPath:
            path: /hyperledger/producer/peer1
        - name: producer-admin-mount
          hostPath:
            path: /hyperledger/producer/admin
        - name: shared-mount
          hostPath:
            path: /hyperledger/shared
        - name: docker-mount
          hostPath:
            path: /var/run/
