apiVersion: v1
kind: Service
metadata:
  name: cli-producer
  labels:
    app: cli-producer
spec:
  type: ClusterIP
  selector:
    app: cli-producer
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000