apiVersion: v1
kind: Service
metadata:
  name: cli-retailer
  labels:
    app: cli-retailer
spec:
  type: ClusterIP
  selector:
    app: cli-retailer
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000