apiVersion: v1
kind: Service
metadata:
  name: cli-retailer-db
spec:
  ports:
    - port: 27017
  selector:
    app: cli-retailer-db
---
apiVersion: v1
kind: Service
metadata:
  name: cli-retailer
  labels:
    app: cli-retailer
spec:
  type: ClusterIP
  selector:
    app: cli-retailer
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-retailer-db
spec:
  selector:
    matchLabels:
      app: cli-retailer-db
  template:
    metadata:
      labels:
        app: cli-retailer-db
    spec:
      containers:
      - name: cli-retailer-db
        image: mongo:latest
        ports:
        - containerPort: 27017
        envFrom:
        - configMapRef:
            name: retailer-cli-db-env-file
        - secretRef:
            name: retailer-cli-db-secret-file
        volumeMounts:
            - mountPath: /data/db
              name: cli-retailer-db-volume
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 20
          timeoutSeconds: 1
      volumes:
      - name: cli-retailer-db-volume
        hostPath:
            path: /cli-retailer-db-volume
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-retailer
  labels:
    app: cli-retailer
spec:
  selector:
    matchLabels:
      app: cli-retailer
  template:
    metadata:
      labels:
        app: cli-retailer
    spec:
      containers:
        - name: cli-retailer
          image: cli
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          tty: true
          workingDir: /tmp/hyperledger/chaincode
          volumeMounts:
            - mountPath: /tmp/hyperledger/retailer/admin
              name: retailer-admin-mount
            - mountPath: /tmp/hyperledger/retailer/peer1
              name: retailer-peer1-mount
            - mountPath: /tmp/hyperledger/scripts
              name: scripts-mount
            - mountPath: /tmp/hyperledger/chaincode
              name: chaincode-mount
            - mountPath: /tmp/hyperledger/shared
              name: shared-mount
            - mountPath: /tmp/hyperledger/app
              name: app-mount
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 3
          env:
            - name: GOPATH
              value: "/opt/gopath"
            - name: CORE_VM_ENDPOINT
              value: "unix:///host/var/run/docker.sock"
            # Uncomment for debugging
            #- name: FABRIC_LOGGING_SPEC
            #  value: "DEBUG"
            - name: CORE_PEER_ID
              value: "cli-retailer"
            - name: CORE_PEER_ADDRESS
              value: "peer1-retailer:7051"
            - name: CORE_PEER_LOCALMSPID
              value: "RetailerMSP"
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/tmp/hyperledger/retailer/peer1/tls-msp/tlscacerts/${PEERS_TLSCACERTS}"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/tmp/hyperledger/retailer/admin/msp"
            - name: ANCHOR_PEER_IP
              value: "peer1-retailer"
            - name: ANCHOR_PEER_PORT
              value: "7051"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "toor"
            - name: DB_HOST
              value: "cli-retailer-db"
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: "admin"
      volumes:
        - name: retailer-peer1-mount
          hostPath:
            path: /hyperledger/retailer/peer1
        - name: retailer-admin-mount
          hostPath:
            path: /hyperledger/retailer/admin
        - name: chaincode-mount
          hostPath:
            path: /hyperledger/chaincode
        - name: scripts-mount
          hostPath:
            path: /hyperledger/scripts
        - name: shared-mount
          hostPath:
            path: /hyperledger/shared
        - name: docker-mount
          hostPath:
            path: /var/run/
        - name: app-mount
          hostPath:
            path: /hyperledger/app/retailer-cli
