apiVersion: apps/v1
kind: Deployment
metadata:
    name: couchdb1
    labels:
        app: couchdb1
spec:
    selector:
        matchLabels:
            app: couchdb1
    template:
        metadata: 
            labels:
                app: couchdb1
        spec:
            containers:
              - name: couchdb1
                image: couchdb:latest
                imagePullPolicy: IfNotPresent
                env:
                - name: COUCHDB_USER
                  value: "admin"
                - name: COUCHDB_PASSWORD
                  value: "adminpw"