apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer
  labels:
    app: orderer
spec:
  selector:
    matchLabels:
      app: orderer
  template:
    metadata:
      labels:
        app: orderer
    spec:
      containers:
        - name: orderer
          image: hyperledger/fabric-orderer:2.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tmp/hyperledger/orderer-org/orderer
              name: orderer-mount
          envFrom:
            - configMapRef:
                name: orderer-env-file
      volumes:
        - name: orderer-mount
          hostPath:
            path: /hyperledger/orderer-org/orderer
