apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer
  labels:
    app: orderer
spec:
  selector:
    matchLabels:
      app: orderer
  template:
    metadata:
      labels:
        app: orderer
    spec:
      containers:
        - name: orderer
          image: hyperledger/fabric-orderer:2.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tmp/hyperledger/orderer-org/orderer
              name: orderer-mount
          env:
            - name: ORDERER_HOME
              value: "/tmp/hyperledger/orderer"
            - name: ORDERER_HOST
              value: "orderer"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: "file"
            - name: ORDERER_GENERAL_GENESISFILE
              value: "/tmp/hyperledger/orderer-org/orderer/genesis.block"
            - name: ORDERER_GENERAL_LOCALMSPID
              value: "OrdererMSP"
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: "/tmp/hyperledger/orderer-org/orderer/msp"
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: "/tmp/hyperledger/orderer-org/orderer/tls-msp/signcerts/cert.pem"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: "/tmp/hyperledger/orderer-org/orderer/tls-msp/keystore/key.pem"
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/tmp/hyperledger/orderer-org/orderer/tls-msp/tlscacerts/${PEERS_TLSCACERTS}]"
            - name: ORDERER_GENERAL_LOGLEVEL
              value: "debug"
            - name: FABRIC_LOGGING_SPEC
              value: "DEBUG"
            - name: ORDERER_DEBUG_BROADCASTTRACEDIR
              value: "data/logs"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: "/tmp/hyperledger/orderer-org/orderer/tls-msp/keystore/key.pem"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: "/tmp/hyperledger/orderer-org/orderer/tls-msp/signcerts/cert.pem"
      volumes:
        - name: orderer-mount
          hostPath:
            path: /hyperledger/orderer-org/orderer
