apiVersion: v1
kind: Service
metadata:
  name: rca-regulatory-department
  labels:
    app: rca-regulatory-department-root
spec:
  type: NodePort
  selector:
    app: rca-regulatory-department-root
  ports:
    - protocol: TCP
      nodePort: 30907
      targetPort: 7054
      port: 7054