apiVersion: v1
kind: Service
metadata:
  name: couchdb3
  labels:
    app: couchdb3
spec:
  type: ClusterIP
  selector:
    app: couchdb3
  ports:
    - protocol: TCP
      targetPort: 5984
      port: 5984