apiVersion: v1
kind: Service
metadata:
  name: rca-manufacturer
  labels:
    app: rca-manufacturer-root
spec:
  type: NodePort
  selector:
    app: rca-manufacturer-root
  ports:
    - protocol: TCP
      nodePort: 30909
      targetPort: 7056
      port: 7056