apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-retailer
  labels:
    app: cli-retailer
spec:
  selector:
    matchLabels:
      app: cli-retailer
  template:
    metadata:
      labels:
        app: cli-retailer
    spec:
      containers:
        - name: cli-org1
          image: hyperledger/fabric-tools:2.2
          imagePullPolicy: IfNotPresent
          tty: true
          command: ["sh"]
          workingDir: /tmp/hyperledger/chaincode
          volumeMounts:
            - mountPath: /tmp/hyperledger/retailer/admin
              name: retailer-admin-mount
            - mountPath: /tmp/hyperledger/retailer/peer1
              name: retailer-peer1-mount
            - mountPath: /tmp/hyperledger/scripts
              name: scripts-mount
            - mountPath: /tmp/hyperledger/chaincode
              name: chaincode-mount
            - mountPath: /tmp/hyperledger/shared
              name: shared-mount
          env:
            - name: GOPATH
              value: "/opt/gopath"
            - name: CORE_VM_ENDPOINT
              value: "unix:///host/var/run/docker.sock"
            # Uncomment for debugging
            #- name: FABRIC_LOGGING_SPEC
            #  value: "DEBUG"
            - name: CORE_PEER_ID
              value: "cli-retailer"
            - name: CORE_PEER_ADDRESS
              value: "peer1-retailer:7051"
            - name: CORE_PEER_LOCALMSPID
              value: "RetailerMSP"
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/tmp/hyperledger/retailer/peer1/tls-msp/tlscacerts/${PEERS_TLSCACERTS}"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/tmp/hyperledger/retailer/admin/msp"
            - name: ANCHOR_PEER_IP
              value: "peer1-retailer"
            - name: ANCHOR_PEER_PORT
              value: "7051"
      volumes:
        - name: retailer-peer1-mount
          hostPath:
            path: /hyperledger/retailer/peer1
        - name: retailer-admin-mount
          hostPath:
            path: /hyperledger/retailer/admin
        - name: chaincode-mount
          hostPath:
            path: /hyperledger/chaincode
        - name: scripts-mount
          hostPath:
            path: /hyperledger/scripts
        - name: shared-mount
          hostPath:
            path: /hyperledger/shared
        - name: docker-mount
          hostPath:
            path: /var/run/
