apiVersion: v1
kind: Service
metadata:
  name: frontend-producer
  labels:
    app: frontend-producer
spec:
  type: ClusterIP
  selector:
    app: frontend-producer
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-producer
  labels:
    app: frontend-producer
spec:
  selector:
    matchLabels:
      app: frontend-producer
  template:
    metadata:
      labels:
        app: frontend-producer
    spec:
      containers:
        - name: frontend-producer
          image: frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: producer-frontend-env-file
