apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer1-retailer
  labels:
    app: peer1-retailer
spec:
  selector:
    matchLabels:
      app: peer1-retailer
  template:
    metadata:
      labels:
        app: peer1-retailer
    spec:
      containers:
        - name: peer1-retailer
          image: hyperledger/fabric-peer:2.2
          volumeMounts:
            - mountPath: /tmp/hyperledger/retailer/peer1
              name: peer1-retailer-mount
          envFrom:
          - configMapRef:
              name: retailer-peer1-env-file
          - secretRef:
              name: retailer-peer1-secret-file
      volumes:
        - name: peer1-retailer-mount
          hostPath:
            path: /hyperledger/retailer/peer1
