apiVersion: v1
kind: Service
metadata:
  name: peer1-retailer
  labels:
    app: peer1-retailer
spec:
  selector:
    app: peer1-retailer
  ports:
    - name: core
      protocol: TCP
      targetPort: 7051
      port: 7051
    - name: chaincode
      protocol: TCP
      targetPort: 7052
      port: 7052
