apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer1-retailer
  labels:
    app: peer1-retailer
spec:
  selector:
    matchLabels:
      app: peer1-retailer
  template:
    metadata:
      labels:
        app: peer1-retailer
    spec:
      containers:
        - name: peer1-retailer
          image: hyperledger/fabric-peer:2.2
          volumeMounts:
            - mountPath: /tmp/hyperledger/retailer/peer1
              name: peer1-retailer-mount
          env:
            - name: CORE_PEER_ID
              value: "peer1-retailer"
            - name: CORE_PEER_LISTENADDRESS
              value: "0.0.0.0:7051"
            - name: CORE_PEER_ADDRESS
              value: "peer1-retailer:7051"
            - name: CORE_PEER_LOCALMSPID
              value: "RetailerMSP"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/tmp/hyperledger/retailer/peer1/msp"
            - name: CORE_VM_ENDPOINT
              value: "tcp://dind:2375"
            - name: FABRIC_LOGGING_SPEC
              value: "debug"
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: "/tmp/hyperledger/retailer/peer1/tls-msp/signcerts/cert.pem"
            - name: CORE_PEER_TLS_KEY_FILE
              value: "/tmp/hyperledger/retailer/peer1/tls-msp/keystore/key.pem"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/tmp/hyperledger/retailer/peer1/tls-msp/tlscacerts/${PEERS_TLSCACERTS}"
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: "peer1-retailer:7051"
            - name: CORE_PEER_BOOTSTRAP
              value: "peer1-retailer:7051"
            - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
              value: "true"
            - name: CORE_PEER_CHAINCODEADDRESS
              value: "peer1-retailer:7052"
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: "0.0.0.0:7052"
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: "CouchDB"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: "couchdb4:5984"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
              value: "admin"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
              value: "adminpw"
      volumes:
        - name: peer1-retailer-mount
          hostPath:
            path: /hyperledger/retailer/peer1
