apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer1-regulatory-department
  labels:
    app: peer1-regulatory-department
spec:
  selector:
    matchLabels:
      app: peer1-regulatory-department
  template:
    metadata:
      labels:
        app: peer1-regulatory-department
    spec:
      containers:
        - name: peer1-regulatory-department
          image: hyperledger/fabric-peer:2.2
          volumeMounts:
            - mountPath: /tmp/hyperledger/regulatory-department/peer1
              name: peer1-regulatory-department-mount
          envFrom:
          - configMapRef:
              name: regulatory-department-peer1-env-file
          - secretRef:
              name: regulatory-department-peer1-secret-file
      volumes:
        - name: peer1-regulatory-department-mount
          hostPath:
            path: /hyperledger/regulatory-department/peer1
