apiVersion: v1
kind: Service
metadata:
  name: cli-regulatory-department
  labels:
    app: cli-regulatory-department
spec:
  type: ClusterIP
  selector:
    app: cli-regulatory-department
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000