apiVersion: apps/v1
kind: Deployment
metadata:
    name: ca-tls
    labels:
        app: ca-tls-root
spec:
    selector:
        matchLabels:
            app: ca-tls-root
    template:
        metadata: 
            labels:
                app: ca-tls-root
        spec:
            containers:
              - name: ca-tls
                image: hyperledger/fabric-ca:1.4.7
                imagePullPolicy: IfNotPresent
                command: ["fabric-ca-server", "start", "-b", "$(RCA_ADMIN_USERNAME):$(RCA_ADMIN_PASSWORD)", "--port", "7052"]
                volumeMounts:
                  - mountPath: /tmp/hyperledger/fabric-ca
                    name: ca-mount
                envFrom:
                  - configMapRef:
                      name: tls-ca-env-file
                  - secretRef:
                      name: tls-ca-secret-file
            volumes:
              - name: ca-mount
                hostPath:
                  path: /hyperledger/tls-ca
