apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer1-deliverer
  labels:
    app: peer1-deliverer
spec:
  selector:
    matchLabels:
      app: peer1-deliverer
  template:
    metadata:
      labels:
        app: peer1-deliverer
    spec:
      containers:
        - name: peer1-deliverer
          image: hyperledger/fabric-peer:2.2
          volumeMounts:
            - mountPath: /tmp/hyperledger/deliverer/peer1
              name: peer1-deliverer-mount
          envFrom:
          - configMapRef:
              name: deliverer-peer1-env-file
          - secretRef:
              name: deliverer-peer1-secret-file
      volumes:
        - name: peer1-deliverer-mount
          hostPath:
            path: /hyperledger/deliverer/peer1
