apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer1-manufacturer
  labels:
    app: peer1-manufacturer
spec:
  selector:
    matchLabels:
      app: peer1-manufacturer
  template:
    metadata:
      labels:
        app: peer1-manufacturer
    spec:
      containers:
        - name: peer1-manufacturer
          image: hyperledger/fabric-peer:2.2
          volumeMounts:
            - mountPath: /tmp/hyperledger/manufacturer/peer1
              name: peer1-manufacturer-mount
          envFrom:
          - configMapRef:
              name: manufacturer-peer1-env-file
          - secretRef:
              name: manufacturer-peer1-secret-file
      volumes:
        - name: peer1-manufacturer-mount
          hostPath:
            path: /hyperledger/manufacturer/peer1
